### ISSUE TITLE
Dataset observation details

### ISSUE THREAD

**Issue by lyshuga** [rail-berkeley/bridge_data_v2#16]
Hi,

Thanks for such and amazing paper and dataset. I was trying to deeply understand the meaning of some observation variables (e.g. joint_effort, difference qpos and state, etc.). I was wondering if there is a list with some details regarding the dataset field description.

**Comment by vyeevani** [comment]
I found how these are extracted by going through the widowx_env in the bridge_data_robot codebase and how those values were pulled from the ros packages provided by interbotix.

**Comment by vyeevani** [comment]
For reference: https://github.com/rail-berkeley/bridge_data_robot/blob/main/widowx_envs/widowx_envs/base/robot_base_env.py#277
