### ISSUE TITLE
Baseline results using the Gripper camera view

### ISSUE THREAD

**Issue by Haichao-Zhang** [rail-berkeley/bridge_data_v2#17]
Thanks for the great dataset!

The baseline results in the paper are using the over-the-shoulder camera view. 
I'm curious have you tried the baselines methods using the gripper camera view, and if yes, can you share some of the results?

Thanks!

**Comment by HomerW** [comment]
Unfortunately, we don't have any results for policies that use the gripper camera view yet. Though we will them share once we've tried this!
