### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Alpslee** [rail-berkeley/bridge_data_v2#2]
ArraySharded = jax.interpreters.pxla.ShardedDeviceArray
AttributeError: module 'jax.interpreters.pxla' has no attribute 'ShardedDeviceArray'

Just tried to run training code:
python experiments/train.py \
    --config experiments/configs/train_config.py:METHOD \
    --bridgedata_config experiments/configs/data_config.py:all \
    --name NAME

**Comment by HomerW** [comment]
I believe this is related to the jax version. Can you check that you have 0.4.13?

**Comment by Alpslee** [comment]
> I believe this is related to the jax version. Can you check that you have 0.4.13?

I checked jax and jaxlib version, it's jax 0.4.13 and jaxlib 0.4.14. Did that cause the conflict ?

**Comment by Alpslee** [comment]
> I believe this is related to the jax version. Can you check that you have 0.4.13?

fixed it, thanks !
