### ISSUE TITLE
Download bridge data V1

### ISSUE THREAD

**Issue by yujiangpu20** [rail-berkeley/bridge_data_v2#35]
Thank you for the excellent dataset. I want to download the original bridge dataset (v1) and just found a link:
https://rail.eecs.berkeley.edu/datasets/bridge_release/raw/bridge_data_v1/
 I was wondering if it is the correct portal. I would greatly appreciate it if you could provide any instructions for downloading via this link!

**Comment by HomerW** [comment]
That link does not actually have the actions. It's only used to host the images to support the widget on the website. 

You can download the full raw data [here](https://rail.eecs.berkeley.edu/datasets/bridge_release/data/) (the demos_8_17.zip file) and then extract the `bridge_data_v1` folder.

**Comment by yujiangpu20** [comment]
Thanks for you reply! I will try it :)
