### ISSUE TITLE
eval.py probably should have an option of accepting local config

### ISSUE THREAD

**Issue by vyeevani** [rail-berkeley/bridge_data_v2#4]
Given that the checkpoints that are provided are provided with the configs as opposed to wandb runs, it would be easiest to provide the option to use those configs directly in eval.py.

Consider something like this (allows for removing wandb dependencies):
flags.DEFINE_multi_string("checkpoint_model_path", None, "Path to checkpoint model", required=True)
flags.DEFINE_multi_string("checkpoint_config_path", None, "Path to checkpoint config", required=True)

def main(_):
    # policies is a dict from run_name to (agent, action_mean, action_std)
    policies = {}
    checkpoint_model_path = FLAGS.checkpoint_model_path[0]
    checkpoint_config_path = FLAGS.checkpoint_config_path[0]
    assert tf.io.gfile.exists(checkpoint_model_path), checkpoint_model_path
    assert tf.io.gfile.exists(checkpoint_config_path), checkpoint_config_path
    agent, action_mean, action_std = load_checkpoint(
        checkpoint_model_path, checkpoint_config_path
    )
    checkpoint_num = int(checkpoint_model_path.split("_")[-1])
    policies[f"{checkpoint_num}"] = (agent, action_mean, action_std)

**Comment by HomerW** [comment]
This would be a nice feature. Would you be able to make a PR with this change?
