### ISSUE TITLE
How to get data categoried by skills or environments?

### ISSUE THREAD

**Issue by Lucca-cherries** [rail-berkeley/bridge_data_v2#8]
Hi! It is mentioned in the paper that the data contain 13 skills and 24 environments. How can I get the respective data from a certain skill or a certain environment? How to process the data so that it is classified and clustered by skills or environments? Thanks in advance for your solutions :)

**Comment by HomerW** [comment]
Answered here: https://github.com/rail-berkeley/bridge_data_v2/issues/6#issuecomment-1718184450
